### ISSUE TITLE
How to install firepath in chrome?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pierretholence/firepath#35]
```
Hi,

I am a newbie to this installation...

Can anyone tell how to install firepath in google-chrome?



```

Original issue reported on code.google.com by `anuragsa...@gmail.com` on 10 Jan 2012 at 3:46

**Comment by sanjayselectorshub** [comment]
Here is the ChroPath extension for Chrome which have many advanced features compare to FirePath- 
Download link of addon-
https://chrome.google.com/webstore/detail/chropath/ljngjbnaijcbncmcnjfhigebomdlkcjo

**Comment by Remigius123** [comment]
how to do that?

**Comment by sanjayselectorshub** [comment]
ChroPath is launched for firefox -
https://addons.mozilla.org/en-US/firefox/addon/chropath-for-firefox/
