### ISSUE TITLE
FirePath not working in Firefox 9.0.1

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pierretholence/firepath#36]
```
What steps will reproduce the problem?
1. Install Firefox 9.0.1
2. Open Contextmenu

What is the expected output? What do you see instead?
I expect to see then FirePath entryin the context menu.
But it is not there

What version of the product are you using? On what operating system?
0.9.7

Please provide any additional information below.

```

Original issue reported on code.google.com by `stefan.s...@gmail.com` on 17 Jan 2012 at 9:57

**Comment by Hanendra** [comment]
To solve the issue follow the below steps-->
1.	Open firefox
2.	Type about:config in the explorer
3.	click on the I uderstand button
4.	Now in the search box enter "browser.tabs.remote.autostart.2" (without quotes) and hit enter
5.	Set the value as false ( you need to click the property to toggle the values)
6.	close the firefox and open again
7.	Launch firebug ...Now you should see your fire path 

* Also check once if "browser.tabs.remote.autostart" is set false. If not then make it false (Though generally by default it will be false)
